/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class CustomerAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount uAcc;
    
    public CustomerAreaJPanel(JPanel userProcessContainer, UserAccount account,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.uAcc = account;
        //valueLabel.setText(enterprise.getName());
        populateRequestTable();
        populatePreviousOrderTable();
        lblCAPCustomerID.setText(account.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcomQuote = new javax.swing.JLabel();
        lblCAPCustomerID = new javax.swing.JLabel();
        btnCAPrefresh = new javax.swing.JButton();
        lblCAPRest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCAPRestaurant = new javax.swing.JTable();
        btnCAPOrder = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCAPPreviousOrders = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcomQuote.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblWelcomQuote.setForeground(new java.awt.Color(102, 102, 102));
        lblWelcomQuote.setText("Welcome");
        jPanel1.add(lblWelcomQuote, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 11, 127, 30));

        lblCAPCustomerID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCAPCustomerID.setForeground(new java.awt.Color(102, 102, 102));
        lblCAPCustomerID.setText("<value>");
        jPanel1.add(lblCAPCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 13, 80, 26));

        btnCAPrefresh.setBackground(new java.awt.Color(31, 189, 214));
        btnCAPrefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCAPrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnCAPrefresh.setText("Refresh");
        btnCAPrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPrefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnCAPrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 48, 89, -1));

        lblCAPRest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCAPRest.setForeground(new java.awt.Color(102, 102, 102));
        lblCAPRest.setText("Restaurant");
        jPanel1.add(lblCAPRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        tblCAPRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant Name", "Location/Address", "Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCAPRestaurant);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 131, 440, 97));

        btnCAPOrder.setBackground(new java.awt.Color(31, 189, 214));
        btnCAPOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCAPOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCAPOrder.setText("Place Order");
        btnCAPOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAPOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnCAPOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 250, 140, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Previous Orders List");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 327, 210, -1));

        tblCAPPreviousOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "Restaurant Name", "Amount", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCAPPreviousOrders);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 367, 438, 141));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCAPrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPrefreshActionPerformed

        populateRequestTable();
        populatePreviousOrderTable();
    }//GEN-LAST:event_btnCAPrefreshActionPerformed

    private void btnCAPOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAPOrderActionPerformed
        int selectedRow = tblCAPRestaurant.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a desires row to see details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Restaurant restaurant = (Restaurant)tblCAPRestaurant.getValueAt(selectedRow, 0);
            MenuJPanel manageMenuPanel=new MenuJPanel(userProcessContainer,uAcc,ecosystem,restaurant);
            userProcessContainer.add("MenuPanel",manageMenuPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }

    }//GEN-LAST:event_btnCAPOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCAPOrder;
    private javax.swing.JButton btnCAPrefresh;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCAPCustomerID;
    private javax.swing.JLabel lblCAPRest;
    private javax.swing.JLabel lblWelcomQuote;
    private javax.swing.JTable tblCAPPreviousOrders;
    private javax.swing.JTable tblCAPRestaurant;
    // End of variables declaration//GEN-END:variables

    public void populateRequestTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tblCAPRestaurant.getModel();
         tblModel.setRowCount(0);
            Object[] row = new Object[3];
            for(Restaurant restaur:ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
                     row[0] = restaur;
                     row[1] = restaur.getAddress();
                     row[2] = restaur.getNumber();
                     tblModel.addRow(row);
            }
    }

    public void populatePreviousOrderTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tblCAPPreviousOrders.getModel();
        tblModel.setRowCount(0);
         
        for (Customer cust:ecosystem.getCustomerDirectory().getCustomerDirectory()) {
           if (cust.getUserName().equals(uAcc.getUsername())) {
            for(Order menu:cust.getOrderList()){
                Object[] row = new Object[4];
                row[0] = menu;
                row[1] = menu.getRestaurantName();
                row[2] = menu.getOrderAmount();
                row[3] = menu.getStatus();
                tblModel.addRow(row);
               }
            }
        }
    }
}
