/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Order.Order;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DeliveryManWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    
    
    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public DeliveryManWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;      
        
        populateODTable();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnODProcess = new javax.swing.JButton();
        btnODRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        lblOrderDetails = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 248, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnODProcess.setBackground(new java.awt.Color(31, 189, 214));
        btnODProcess.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnODProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnODProcess.setText("Process");
        btnODProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnODProcessActionPerformed(evt);
            }
        });
        add(btnODProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        btnODRefresh.setBackground(new java.awt.Color(31, 189, 214));
        btnODRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnODRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnODRefresh.setText("Refresh");
        btnODRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnODRefreshActionPerformed(evt);
            }
        });
        add(btnODRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, -1));

        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "OrderID", "RestaurantName", "Customer Name", "Delivery Address", "Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrderDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 58, 650, 170));

        lblOrderDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOrderDetails.setForeground(new java.awt.Color(102, 102, 102));
        lblOrderDetails.setText("Details of Order");
        add(lblOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnODProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnODProcessActionPerformed
        
        int highlightedRow = tblOrderDetails.getSelectedRow();
        
        if (highlightedRow < 0){
            return;
        }
        
        Order order = (Order)tblOrderDetails.getValueAt(highlightedRow, 0); 
        ProcessWorkRequestJPanel processWorkRequestJPanel = new ProcessWorkRequestJPanel(userProcessContainer, order);
        userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnODProcessActionPerformed

    private void btnODRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnODRefreshActionPerformed
        populateODTable();
    }//GEN-LAST:event_btnODRefreshActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnODProcess;
    private javax.swing.JButton btnODRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOrderDetails;
    private javax.swing.JTable tblOrderDetails;
    // End of variables declaration//GEN-END:variables

    public void populateODTable() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    DefaultTableModel tblModel = (DefaultTableModel) tblOrderDetails.getModel();
        
        tblModel.setRowCount(0);
        
        for(DeliveryMan deliveryMan : business.getDeliveryManDirectory().getDeliveryManDirectory()){
            if(deliveryMan.getUserName().equals(userAccount.getUsername())){
                    
                for(Order order : deliveryMan.getOrderList()){
                Object[] rowNo = new Object[6];                 
                rowNo[4] = order.getOrderAmount();
                rowNo[5] = order.getStatus();
                rowNo[0] = order;
                rowNo[1] = order.getRestaurantName();
                rowNo[2] = order.getCustomerName();
                rowNo[3] = order.getAddress();
                tblModel.addRow(rowNo);
                    
                }
            }
            
        }
    
    
    }
}
