/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managePanels;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class MngCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MngCustomersJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAcc;
    
    public MngCustomersJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateCustomerListTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblmngCustomers = new javax.swing.JLabel();
        mcBackBtn = new javax.swing.JButton();
        mcNamelbl = new javax.swing.JLabel();
        mcUnamelbl = new javax.swing.JLabel();
        mcPwdlbl = new javax.swing.JLabel();
        mcNameTextField = new javax.swing.JTextField();
        mcUnameTextField = new javax.swing.JTextField();
        mcPwdTextField = new javax.swing.JTextField();
        mcAddCustomerbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mcListTable = new javax.swing.JTable();
        mcEditbtn = new javax.swing.JButton();
        mcDeletebtn = new javax.swing.JButton();
        mcSavebtn = new javax.swing.JButton();
        mcNumberlbl = new javax.swing.JLabel();
        mcAddresslbl = new javax.swing.JLabel();
        mcAddressTextField = new javax.swing.JTextField();
        mcNumberTextField = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblmngCustomers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmngCustomers.setForeground(new java.awt.Color(102, 102, 102));
        lblmngCustomers.setText("Manage Customers ");
        jPanel1.add(lblmngCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        mcBackBtn.setBackground(new java.awt.Color(102, 102, 102));
        mcBackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mcBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        mcBackBtn.setText("<");
        mcBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mcBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        mcNamelbl.setText("Name :");
        jPanel1.add(mcNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        mcUnamelbl.setText("Username :");
        jPanel1.add(mcUnamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        mcPwdlbl.setText("Password :");
        jPanel1.add(mcPwdlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        mcNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mcNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 183, -1));

        mcUnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcUnameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mcUnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 183, -1));
        jPanel1.add(mcPwdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 183, -1));

        mcAddCustomerbtn.setBackground(new java.awt.Color(31, 189, 214));
        mcAddCustomerbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcAddCustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        mcAddCustomerbtn.setText("Add Customer");
        mcAddCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcAddCustomerbtnActionPerformed(evt);
            }
        });
        jPanel1.add(mcAddCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        mcListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(mcListTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 590, 119));

        mcEditbtn.setBackground(new java.awt.Color(31, 189, 214));
        mcEditbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcEditbtn.setForeground(new java.awt.Color(255, 255, 255));
        mcEditbtn.setText("Edit");
        mcEditbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcEditbtnActionPerformed(evt);
            }
        });
        jPanel1.add(mcEditbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 65, -1));

        mcDeletebtn.setBackground(new java.awt.Color(31, 189, 214));
        mcDeletebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcDeletebtn.setForeground(new java.awt.Color(255, 255, 255));
        mcDeletebtn.setText("Delete");
        mcDeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcDeletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(mcDeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        mcSavebtn.setBackground(new java.awt.Color(31, 189, 214));
        mcSavebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mcSavebtn.setForeground(new java.awt.Color(255, 255, 255));
        mcSavebtn.setText("Save");
        mcSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcSavebtnActionPerformed(evt);
            }
        });
        jPanel1.add(mcSavebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 65, -1));

        mcNumberlbl.setText("PhNumber :");
        jPanel1.add(mcNumberlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        mcAddresslbl.setText("Address :");
        jPanel1.add(mcAddresslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        mcAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcAddressTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(mcAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 183, -1));
        jPanel1.add(mcNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 183, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mcBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcBackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardlout = (CardLayout) userProcessContainer.getLayout();
        cardlout.previous(userProcessContainer);
        
    }//GEN-LAST:event_mcBackBtnActionPerformed

    private void mcNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcNameTextFieldActionPerformed

    private void mcUnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcUnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcUnameTextFieldActionPerformed

    private void mcAddCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcAddCustomerbtnActionPerformed
        // TODO add your handling code here:
        
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(mcUnameTextField.getText())){
            UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(mcNameTextField.getText(), mcUnameTextField.getText(), mcPwdTextField.getText(), null, new CustomerRole());
            Customer customer = ecosystem.getCustomerDirectory().createUserAccount(mcNameTextField.getText(), mcUnameTextField.getText(), mcPwdTextField.getText(),mcAddressTextField.getText(),mcNumberTextField.getText());
            populateCustomerListTable();
            mcNameTextField.setText("");
            mcUnameTextField.setText("");
            mcPwdTextField.setText("");
            mcAddressTextField.setText("");
            mcNumberTextField.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Username exists! Please provide the different one!");
        }
    }//GEN-LAST:event_mcAddCustomerbtnActionPerformed

    private void mcDeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcDeletebtnActionPerformed
        // TODO add your handling code here:
        int highlightedRow = mcListTable.getSelectedRow();
        if(highlightedRow >= 0){
            String username = (String) mcListTable.getValueAt(highlightedRow, 1);
            ecosystem.getCustomerDirectory().deleteCustomer(username);
            ecosystem.getUserAccountDirectory().deleteUserAccount(userAcc);
            populateCustomerListTable();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the row to delete");
        }
    }//GEN-LAST:event_mcDeletebtnActionPerformed

    private void mcEditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcEditbtnActionPerformed
        // TODO add your handling code here:
        int highlightedRow = mcListTable.getSelectedRow();
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        if(highlightedRow >= 0){
            String username = (String) mcListTable.getValueAt(highlightedRow, 1);
            Customer custmr = ecosystem.getCustomerDirectory().getCustomer(username);
            mcNameTextField.setText(custmr.getName());
            mcUnameTextField.setText(custmr.getUserName());
            mcPwdTextField.setText(custmr.getPassword());
            this.userAcc = ecosystem.getUserAccountDirectory().authenticateUser(username, custmr.getPassword());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the desired row to edit");
        }
    }//GEN-LAST:event_mcEditbtnActionPerformed

    private void mcSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcSavebtnActionPerformed
        // TODO add your handling code here:
        
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        ecosystem.getUserAccountDirectory().editUserAccount(this.userAcc,mcNameTextField.getText(), mcUnameTextField.getText(), mcPwdTextField.getText());
        ecosystem.getCustomerDirectory().editCustomer(mcNameTextField.getText(), mcUnameTextField.getText(), mcPwdTextField.getText());
        mcNameTextField.setText("");
        mcUnameTextField.setText("");
        mcPwdTextField.setText("");
        populateCustomerListTable();
    }//GEN-LAST:event_mcSavebtnActionPerformed

    private void mcAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mcAddressTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblmngCustomers;
    private javax.swing.JButton mcAddCustomerbtn;
    private javax.swing.JTextField mcAddressTextField;
    private javax.swing.JLabel mcAddresslbl;
    private javax.swing.JButton mcBackBtn;
    private javax.swing.JButton mcDeletebtn;
    private javax.swing.JButton mcEditbtn;
    private javax.swing.JTable mcListTable;
    private javax.swing.JTextField mcNameTextField;
    private javax.swing.JLabel mcNamelbl;
    private javax.swing.JTextField mcNumberTextField;
    private javax.swing.JLabel mcNumberlbl;
    private javax.swing.JTextField mcPwdTextField;
    private javax.swing.JLabel mcPwdlbl;
    private javax.swing.JButton mcSavebtn;
    private javax.swing.JTextField mcUnameTextField;
    private javax.swing.JLabel mcUnamelbl;
    // End of variables declaration//GEN-END:variables

    private void populateCustomerListTable() {
        ArrayList<Customer> directory = ecosystem.getCustomerDirectory().getCustomerDirectory();
        DefaultTableModel tableModel = (DefaultTableModel)mcListTable.getModel();
        tableModel.setRowCount(0);
        
        for(Customer customer: directory){
        
            Object [] row = new Object[5];
            row[0] = customer.getName();
            row[1] = customer.getUserName();
            row[2] = customer.getPassword();
            row[3] = customer.getAddress();
            row[4] = customer.getPhoneNum();
            tableModel.addRow(row);
        }
    }
}
