/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managePanels;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Role.DeliverManRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class MngDeliveryManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MngDeliveryManJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAcc;
    
    public MngDeliveryManJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        displayTableDMList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDMBack = new javax.swing.JButton();
        lblMainMR = new javax.swing.JLabel();
        lblDMName = new javax.swing.JLabel();
        lblDMUsername = new javax.swing.JLabel();
        lblDMPassword = new javax.swing.JLabel();
        txtfDMName = new javax.swing.JTextField();
        txtfDMUsername = new javax.swing.JTextField();
        txtfDMPassword = new javax.swing.JTextField();
        btnDMRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDMList = new javax.swing.JTable();
        btnDMEdit = new javax.swing.JButton();
        btnDMDelete = new javax.swing.JButton();
        btnDMSave = new javax.swing.JButton();
        lblDMAddress = new javax.swing.JLabel();
        txtfDMAddress = new javax.swing.JTextField();
        lblDMPhnumber = new javax.swing.JLabel();
        txtfDMPhnumber = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDMBack.setBackground(new java.awt.Color(102, 102, 102));
        btnDMBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDMBack.setForeground(new java.awt.Color(255, 255, 255));
        btnDMBack.setText("<");
        btnDMBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnDMBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 51, 39));

        lblMainMR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMainMR.setForeground(new java.awt.Color(102, 102, 102));
        lblMainMR.setText("Manage Delivery Man");
        jPanel1.add(lblMainMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, 183, 39));

        lblDMName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMName.setText("Name:");
        jPanel1.add(lblDMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 68, -1, -1));

        lblDMUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMUsername.setText("Username:");
        jPanel1.add(lblDMUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblDMPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMPassword.setText("Password:");
        jPanel1.add(lblDMPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel1.add(txtfDMName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 30));

        txtfDMUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDMUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfDMUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));
        jPanel1.add(txtfDMPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        btnDMRegister.setBackground(new java.awt.Color(31, 189, 214));
        btnDMRegister.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDMRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnDMRegister.setText("Register");
        btnDMRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnDMRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 258, 118, 30));

        tblDMList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblDMList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 536, 127));

        btnDMEdit.setBackground(new java.awt.Color(31, 189, 214));
        btnDMEdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDMEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnDMEdit.setText("Edit");
        btnDMEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnDMEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 465, 65, -1));

        btnDMDelete.setBackground(new java.awt.Color(31, 189, 214));
        btnDMDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDMDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDMDelete.setText("Delete");
        btnDMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDMDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 465, -1, -1));

        btnDMSave.setBackground(new java.awt.Color(31, 189, 214));
        btnDMSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDMSave.setForeground(new java.awt.Color(255, 255, 255));
        btnDMSave.setText("Save");
        btnDMSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDMSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnDMSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 465, 65, -1));

        lblDMAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMAddress.setText("Address:");
        jPanel1.add(lblDMAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 218, -1, -1));

        txtfDMAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfDMAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtfDMAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 208, 180, 30));

        lblDMPhnumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDMPhnumber.setText("PhNumber:");
        jPanel1.add(lblDMPhnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 268, 62, -1));
        jPanel1.add(txtfDMPhnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 258, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDMBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLout = (CardLayout) userProcessContainer.getLayout();
        cardLout.previous(userProcessContainer);
    }//GEN-LAST:event_btnDMBackActionPerformed

    private void txtfDMUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDMUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDMUsernameActionPerformed

    private void btnDMRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMRegisterActionPerformed
        // TODO add your handling code here:
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtfDMName.getText())){
            UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText(), null, new DeliverManRole());
            DeliveryMan dm = ecosystem.getDeliveryManDirectory().createUserAccount(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText(),txtfDMAddress.getText(),txtfDMPhnumber.getText());
            displayTableDMList();
            txtfDMName.setText("");
            txtfDMUsername.setText("");
            txtfDMPassword.setText("");
            txtfDMAddress.setText("");
            txtfDMPhnumber.setText("");

        }
        else{
            JOptionPane.showMessageDialog(null, "Username exists! Please provide the different one!");
        }
    }//GEN-LAST:event_btnDMRegisterActionPerformed

    private void btnDMEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMEditActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblDMList.getSelectedRow();
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        if(highlightedRow >= 0){
            String username = (String) tblDMList.getValueAt(highlightedRow, 1);
            DeliveryMan dm = ecosystem.getDeliveryManDirectory().getDeliveryMan(username);
            txtfDMName.setText(dm.getName());
            txtfDMUsername.setText(dm.getUserName());
            txtfDMPassword.setText(dm.getPassword());
            this.userAcc = ecosystem.getUserAccountDirectory().authenticateUser(username, dm.getPassword());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the desired row to edit");
        }
    }//GEN-LAST:event_btnDMEditActionPerformed

    private void btnDMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMDeleteActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblDMList.getSelectedRow();
        if(highlightedRow >= 0){
            String username = (String) tblDMList.getValueAt(highlightedRow, 1);
            ecosystem.getDeliveryManDirectory().deleteDeliveryMan(username);
            ecosystem.getUserAccountDirectory().deleteUserAccount(userAcc);
            displayTableDMList();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the row to delete");
        }
    }//GEN-LAST:event_btnDMDeleteActionPerformed

    private void btnDMSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDMSaveActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        ecosystem.getUserAccountDirectory().editUserAccount(this.userAcc,txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText());
        ecosystem.getDeliveryManDirectory().editDeliveryMan(txtfDMName.getText(), txtfDMUsername.getText(), txtfDMPassword.getText());
        txtfDMName.setText("");
        txtfDMUsername.setText("");
        txtfDMPassword.setText("");
        displayTableDMList();

    }//GEN-LAST:event_btnDMSaveActionPerformed

    private void txtfDMAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfDMAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfDMAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDMBack;
    private javax.swing.JButton btnDMDelete;
    private javax.swing.JButton btnDMEdit;
    private javax.swing.JButton btnDMRegister;
    private javax.swing.JButton btnDMSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDMAddress;
    private javax.swing.JLabel lblDMName;
    private javax.swing.JLabel lblDMPassword;
    private javax.swing.JLabel lblDMPhnumber;
    private javax.swing.JLabel lblDMUsername;
    private javax.swing.JLabel lblMainMR;
    private javax.swing.JTable tblDMList;
    private javax.swing.JTextField txtfDMAddress;
    private javax.swing.JTextField txtfDMName;
    private javax.swing.JTextField txtfDMPassword;
    private javax.swing.JTextField txtfDMPhnumber;
    private javax.swing.JTextField txtfDMUsername;
    // End of variables declaration//GEN-END:variables

    private void displayTableDMList() {
        
        ArrayList<DeliveryMan> dmDirectory = ecosystem.getDeliveryManDirectory().getDeliveryManDirectory();
        DefaultTableModel tableModel = (DefaultTableModel)tblDMList.getModel();
        tableModel.setRowCount(0);
        
        for(DeliveryMan dm: dmDirectory){
        
            Object [] row = new Object[3];
            row[0] = dm.getName();
            row[1] = dm.getUserName();
            row[2] = dm.getPassword();
            tableModel.addRow(row);
        }
    }
}
