/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managePanels;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Role.AdminRole;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class MngRestaurantsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MngRestaurantsJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount userAcc;
    
    public MngRestaurantsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        displayTableMRList();
    }

//    public MngRestaurantsJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBackMR = new javax.swing.JButton();
        lblMainMR = new javax.swing.JLabel();
        lblMRName = new javax.swing.JLabel();
        lblMRUsername = new javax.swing.JLabel();
        lblMRPassword = new javax.swing.JLabel();
        txtfName = new javax.swing.JTextField();
        txtfUsername = new javax.swing.JTextField();
        txtfPassword = new javax.swing.JTextField();
        btnRestaurantRegister = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMRList = new javax.swing.JTable();
        btnMREdit = new javax.swing.JButton();
        btnMRDelete = new javax.swing.JButton();
        btnMRSave = new javax.swing.JButton();
        txtfMRAddress = new javax.swing.JTextField();
        lblMRAddress = new javax.swing.JLabel();
        lblMRPhNumber = new javax.swing.JLabel();
        txtfMRPhNumber = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackMR.setBackground(new java.awt.Color(102, 102, 102));
        btnBackMR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackMR.setForeground(new java.awt.Color(255, 255, 255));
        btnBackMR.setText("<");
        btnBackMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMRActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 51, 39));

        lblMainMR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMainMR.setForeground(new java.awt.Color(102, 102, 102));
        lblMainMR.setText("Manage Restaurants");
        jPanel1.add(lblMainMR, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 11, 150, 39));

        lblMRName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMRName.setText("Name:");
        jPanel1.add(lblMRName, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 68, -1, -1));

        lblMRUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMRUsername.setText("Username:");
        jPanel1.add(lblMRUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblMRPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMRPassword.setText("Password:");
        jPanel1.add(lblMRPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel1.add(txtfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 30));

        txtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));
        jPanel1.add(txtfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        btnRestaurantRegister.setBackground(new java.awt.Color(31, 189, 214));
        btnRestaurantRegister.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRestaurantRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurantRegister.setText("Register");
        btnRestaurantRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestaurantRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 118, 30));

        tblMRList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(tblMRList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 536, 127));

        btnMREdit.setBackground(new java.awt.Color(31, 189, 214));
        btnMREdit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMREdit.setForeground(new java.awt.Color(255, 255, 255));
        btnMREdit.setText("Edit");
        btnMREdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMREditActionPerformed(evt);
            }
        });
        jPanel1.add(btnMREdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 65, -1));

        btnMRDelete.setBackground(new java.awt.Color(31, 189, 214));
        btnMRDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMRDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnMRDelete.setText("Delete");
        btnMRDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMRDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        btnMRSave.setBackground(new java.awt.Color(31, 189, 214));
        btnMRSave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMRSave.setForeground(new java.awt.Color(255, 255, 255));
        btnMRSave.setText("Save");
        btnMRSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnMRSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 65, -1));

        txtfMRAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfMRAddressActionPerformed(evt);
            }
        });
        jPanel1.add(txtfMRAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 30));

        lblMRAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMRAddress.setText("Address:");
        jPanel1.add(lblMRAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblMRPhNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMRPhNumber.setText("Ph.Number:");
        jPanel1.add(lblMRPhNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));
        jPanel1.add(txtfMRPhNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfUsernameActionPerformed

    private void btnMREditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMREditActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblMRList.getSelectedRow();
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        if(highlightedRow >= 0){
            String username = (String) tblMRList.getValueAt(highlightedRow, 1);
            Restaurant restaurant = ecosystem.getRestaurantDirectory().getRestaurant(username);
            txtfName.setText(restaurant.getName());
            txtfUsername.setText(restaurant.getUserName());
            txtfPassword.setText(restaurant.getPassword());
            this.userAcc = ecosystem.getUserAccountDirectory().authenticateUser(username, restaurant.getPassword());
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the desired row to edit");
        }
    }//GEN-LAST:event_btnMREditActionPerformed

    private void btnMRDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRDeleteActionPerformed
        // TODO add your handling code here:
        int highlightedRow = tblMRList.getSelectedRow();
        if(highlightedRow >= 0){
            String username = (String) tblMRList.getValueAt(highlightedRow, 1);
            ecosystem.getRestaurantDirectory().deleteRestaurant(username);
            ecosystem.getUserAccountDirectory().deleteUserAccount(userAcc);
            displayTableMRList();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select the row to delete");
        }
    }//GEN-LAST:event_btnMRDeleteActionPerformed

    private void btnBackMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMRActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLout = (CardLayout) userProcessContainer.getLayout();
        cardLout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackMRActionPerformed

    private void btnRestaurantRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantRegisterActionPerformed
        // TODO add your handling code here:
        if(ecosystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtfName.getText())){
            UserAccount userAccount = ecosystem.getUserAccountDirectory().createUserAccount(txtfName.getText(), txtfUsername.getText(), txtfPassword.getText(), null, new AdminRole());
            Restaurant restaurant = ecosystem.getRestaurantDirectory().createUserAccount(txtfName.getText(), txtfUsername.getText(), txtfPassword.getText(),txtfMRAddress.getText(),txtfMRPhNumber.getText());
            displayTableMRList();
            txtfName.setText("");
            txtfUsername.setText("");
            txtfPassword.setText("");
            txtfMRAddress.setText("");
            txtfMRPhNumber.setText("");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Username exists! Please provide the different one!");
        }
    }//GEN-LAST:event_btnRestaurantRegisterActionPerformed

    private void btnMRSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRSaveActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory userAcc = ecosystem.getUserAccountDirectory();
        ecosystem.getUserAccountDirectory().editUserAccount(this.userAcc,txtfName.getText(), txtfUsername.getText(), txtfPassword.getText());
        ecosystem.getRestaurantDirectory().editRestaurant(txtfName.getText(), txtfUsername.getText(), txtfPassword.getText());
        txtfName.setText("");
        txtfUsername.setText("");
        txtfPassword.setText("");
        displayTableMRList();
        
    }//GEN-LAST:event_btnMRSaveActionPerformed

    private void txtfMRAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfMRAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfMRAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMR;
    private javax.swing.JButton btnMRDelete;
    private javax.swing.JButton btnMREdit;
    private javax.swing.JButton btnMRSave;
    private javax.swing.JButton btnRestaurantRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMRAddress;
    private javax.swing.JLabel lblMRName;
    private javax.swing.JLabel lblMRPassword;
    private javax.swing.JLabel lblMRPhNumber;
    private javax.swing.JLabel lblMRUsername;
    private javax.swing.JLabel lblMainMR;
    private javax.swing.JTable tblMRList;
    private javax.swing.JTextField txtfMRAddress;
    private javax.swing.JTextField txtfMRPhNumber;
    private javax.swing.JTextField txtfName;
    private javax.swing.JTextField txtfPassword;
    private javax.swing.JTextField txtfUsername;
    // End of variables declaration//GEN-END:variables

    private void displayTableMRList() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        ArrayList<Restaurant> restDirectory = ecosystem.getRestaurantDirectory().getRestaurantDirectory();
        DefaultTableModel tableModel = (DefaultTableModel)tblMRList.getModel();
        tableModel.setRowCount(0);
        
        for(Restaurant restaurant: restDirectory){
        
            Object [] row = new Object[3];
            row[0] = restaurant.getName();
            row[1] = restaurant.getUserName();
            row[2] = restaurant.getPassword();
            tableModel.addRow(row);
        }
    
    
    }
}
