

package userinterface.RestaurantAdminRole;


import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount account;
    
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;      
        lblValueRestName.setText(account.getUsername());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMngRestInfo = new javax.swing.JButton();
        btnMngMenu = new javax.swing.JButton();
        btnAWAMngOrders = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        lblValueRestName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(243, 248, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnMngRestInfo.setBackground(new java.awt.Color(31, 189, 214));
        btnMngRestInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMngRestInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnMngRestInfo.setText("Manage Restaurant Info");
        btnMngRestInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngRestInfoActionPerformed(evt);
            }
        });
        add(btnMngRestInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, -1));

        btnMngMenu.setBackground(new java.awt.Color(31, 189, 214));
        btnMngMenu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMngMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMngMenu.setText("Manage menu");
        btnMngMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngMenuActionPerformed(evt);
            }
        });
        add(btnMngMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, -1));

        btnAWAMngOrders.setBackground(new java.awt.Color(31, 189, 214));
        btnAWAMngOrders.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAWAMngOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnAWAMngOrders.setText("Manage Orders");
        btnAWAMngOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAWAMngOrdersActionPerformed(evt);
            }
        });
        add(btnAWAMngOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 102, 102));
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 120, 30));

        lblValueRestName.setForeground(new java.awt.Color(102, 102, 102));
        lblValueRestName.setText("<value>");
        add(lblValueRestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngRestInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngRestInfoActionPerformed
        // TODO add your handling code here:
        ManageRestInfoJPanel manageRestroJPanel = new ManageRestInfoJPanel(userProcessContainer, account, ecosystem);
       userProcessContainer.add("ManageRestroInfo", manageRestroJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMngRestInfoActionPerformed

    private void btnMngMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngMenuActionPerformed
       MngMenuJPanel managemenuJPanel = new MngMenuJPanel(userProcessContainer, account, ecosystem);
       userProcessContainer.add("ManageMenu", managemenuJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngMenuActionPerformed

    private void btnAWAMngOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAWAMngOrdersActionPerformed
       MngOrdersJPanel manageorderJPanel = new MngOrdersJPanel(userProcessContainer, account, ecosystem);
       userProcessContainer.add("ManageOrders", manageorderJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAWAMngOrdersActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAWAMngOrders;
    private javax.swing.JButton btnMngMenu;
    private javax.swing.JButton btnMngRestInfo;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblValueRestName;
    // End of variables declaration//GEN-END:variables
    
}
