/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Order.Order;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class DeliveryAssignmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAssignmentJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Order order;
    private EcoSystem ecosystem;
    
    
    public DeliveryAssignmentJPanel(JPanel userProcessContainer, UserAccount account, Order order, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.order = order;
        this.ecosystem = ecosystem;
        fillDADeliveryManTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDAOrderAssignment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDADeliveryMan = new javax.swing.JTable();
        btnDABack = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDAOrderAssignment.setBackground(new java.awt.Color(31, 189, 214));
        btnDAOrderAssignment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDAOrderAssignment.setForeground(new java.awt.Color(255, 255, 255));
        btnDAOrderAssignment.setText("ASSIGN ORDER");
        btnDAOrderAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDAOrderAssignmentActionPerformed(evt);
            }
        });
        jPanel1.add(btnDAOrderAssignment, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 218, 210, -1));

        tblDADeliveryMan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserName"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDADeliveryMan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 76, 577, 100));

        btnDABack.setBackground(new java.awt.Color(102, 102, 102));
        btnDABack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDABack.setForeground(new java.awt.Color(255, 255, 255));
        btnDABack.setText("<");
        btnDABack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDABackActionPerformed(evt);
            }
        });
        jPanel1.add(btnDABack, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 24, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDAOrderAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDAOrderAssignmentActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDADeliveryMan.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to assign the order","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {

            DeliveryMan deliveryMan  = (DeliveryMan)tblDADeliveryMan.getValueAt(selectedRow, 0);
            deliveryMan.getOrderList().add(order);
            order.setStatus("Assigned to Deliveryman");
            JOptionPane.showMessageDialog(null, "Assigned to Delivery Man");

        }
    }//GEN-LAST:event_btnDAOrderAssignmentActionPerformed

    private void btnDABackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDABackActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnDABackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDABack;
    private javax.swing.JButton btnDAOrderAssignment;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDADeliveryMan;
    // End of variables declaration//GEN-END:variables

    private void fillDADeliveryManTable() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblDADeliveryMan.getModel();
        tablemodel.setRowCount(0);
        for(DeliveryMan deliveryMan:ecosystem.getDeliveryManDirectory().getDeliveryManDirectory()){
               Object[] row = new Object[1];
               row[0] = deliveryMan;
               tablemodel.addRow(row);
        }
    }
}
