/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sushm
 */
public class ManageRestInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestInfoJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    private UserAccount account;
    
    
    public ManageRestInfoJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        txtfMRIUsername.setText(account.getUsername());
        fillTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMRIAddress = new javax.swing.JLabel();
        txtfMRIRestaurantName = new javax.swing.JTextField();
        txtfMRIPhoneNumber = new javax.swing.JTextField();
        txtfMRIAddress = new javax.swing.JTextField();
        lblRestInfo = new javax.swing.JLabel();
        btnMRIUpdate = new javax.swing.JButton();
        btnMRISave = new javax.swing.JButton();
        lblMRIUsername = new javax.swing.JLabel();
        txtfMRIUsername = new javax.swing.JTextField();
        lblRestName = new javax.swing.JLabel();
        btnMRIBack = new javax.swing.JButton();
        lblPhnum = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(243, 248, 249));

        lblMRIAddress.setText("Address:");

        txtfMRIRestaurantName.setEnabled(false);

        txtfMRIPhoneNumber.setEnabled(false);

        txtfMRIAddress.setEnabled(false);

        lblRestInfo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRestInfo.setForeground(new java.awt.Color(102, 102, 102));
        lblRestInfo.setText("Restaurant Info");

        btnMRIUpdate.setBackground(new java.awt.Color(31, 189, 214));
        btnMRIUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMRIUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnMRIUpdate.setText("Update");
        btnMRIUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRIUpdateActionPerformed(evt);
            }
        });

        btnMRISave.setBackground(new java.awt.Color(31, 189, 214));
        btnMRISave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMRISave.setForeground(new java.awt.Color(255, 255, 255));
        btnMRISave.setText("Save");
        btnMRISave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRISaveActionPerformed(evt);
            }
        });

        lblMRIUsername.setText("User Name:");

        txtfMRIUsername.setEnabled(false);

        lblRestName.setText("Restaurant Name:");

        btnMRIBack.setBackground(new java.awt.Color(102, 102, 102));
        btnMRIBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMRIBack.setForeground(new java.awt.Color(255, 255, 255));
        btnMRIBack.setText("<");
        btnMRIBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRIBackActionPerformed(evt);
            }
        });

        lblPhnum.setText("Phone Number:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnMRIBack)
                .addGap(18, 18, 18)
                .addComponent(lblRestInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblMRIUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtfMRIUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblRestName, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtfMRIRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblPhnum, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtfMRIPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(lblMRIAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtfMRIAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(btnMRIUpdate)
                .addGap(9, 9, 9)
                .addComponent(btnMRISave, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMRIBack)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblRestInfo)))
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMRIUsername))
                    .addComponent(txtfMRIUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblRestName))
                    .addComponent(txtfMRIRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblPhnum))
                    .addComponent(txtfMRIPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMRIAddress))
                    .addComponent(txtfMRIAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMRIUpdate)
                    .addComponent(btnMRISave)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMRIUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRIUpdateActionPerformed
        // TODO add your handling code here:
        txtfMRIPhoneNumber.setEnabled(true);
        txtfMRIRestaurantName.setEnabled(true);
        txtfMRIAddress.setEnabled(true);
        btnMRIUpdate.setEnabled(false);
    }//GEN-LAST:event_btnMRIUpdateActionPerformed

    private void btnMRISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRISaveActionPerformed
        // TODO add your handling code here:

        for(Restaurant restro: ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restro.getUserName().equals(account.getUsername())){
                ecosystem.getRestaurantDirectory().updateRestaurantInfo(restro, txtfMRIRestaurantName.getText(), txtfMRIPhoneNumber.getText(), txtfMRIAddress.getText());
            }
        }

        btnMRIUpdate.setEnabled(true);
        txtfMRIRestaurantName.setEnabled(false);
        txtfMRIAddress.setEnabled(false);
        txtfMRIPhoneNumber.setEnabled(false);
    }//GEN-LAST:event_btnMRISaveActionPerformed

    private void btnMRIBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRIBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnMRIBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMRIBack;
    private javax.swing.JButton btnMRISave;
    private javax.swing.JButton btnMRIUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMRIAddress;
    private javax.swing.JLabel lblMRIUsername;
    private javax.swing.JLabel lblPhnum;
    private javax.swing.JLabel lblRestInfo;
    private javax.swing.JLabel lblRestName;
    private javax.swing.JTextField txtfMRIAddress;
    private javax.swing.JTextField txtfMRIPhoneNumber;
    private javax.swing.JTextField txtfMRIRestaurantName;
    private javax.swing.JTextField txtfMRIUsername;
    // End of variables declaration//GEN-END:variables

    private void fillTextFields() {
        for(Restaurant restaurant: ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restaurant.getUserName().equals(account.getUsername())){
                txtfMRIRestaurantName.setText(restaurant.getName());
                txtfMRIAddress.setText(restaurant.getAddress());
               txtfMRIPhoneNumber.setText(restaurant.getNumber());
            }
        }        
    }
}
