/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Dishlist;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sushm
 */
public class MngMenuJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MngMenuJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EcoSystem ecosystem;
    private Dishlist menu;
    
    
    public MngMenuJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.ecosystem = ecosystem;
        displayFoodCatalogue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMMBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMMFoodname = new javax.swing.JLabel();
        txtfMMFoodName = new javax.swing.JTextField();
        lblMMFoodDesc = new javax.swing.JLabel();
        txtMMFoodDescription = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtMMPrice = new javax.swing.JTextField();
        btnMMAddFoodItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMMCatalogue = new javax.swing.JTable();
        btnMMDelete = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(243, 248, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMMBack.setBackground(new java.awt.Color(102, 102, 102));
        btnMMBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMMBack.setForeground(new java.awt.Color(255, 255, 255));
        btnMMBack.setText("<");
        btnMMBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnMMBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Menu Catalogue");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 15, 147, -1));

        lblMMFoodname.setText("Food Name:");
        jPanel1.add(lblMMFoodname, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 66, -1, -1));
        jPanel1.add(txtfMMFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 63, 135, -1));

        lblMMFoodDesc.setText("Food Description:");
        jPanel1.add(lblMMFoodDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 104, -1, -1));
        jPanel1.add(txtMMFoodDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 101, 135, -1));

        lblPrice.setText("Price:");
        jPanel1.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 142, -1, -1));

        txtMMPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtMMPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 139, 135, -1));

        btnMMAddFoodItem.setBackground(new java.awt.Color(31, 189, 214));
        btnMMAddFoodItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMMAddFoodItem.setForeground(new java.awt.Color(255, 255, 255));
        btnMMAddFoodItem.setText("+ ADD");
        btnMMAddFoodItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMAddFoodItemActionPerformed(evt);
            }
        });
        jPanel1.add(btnMMAddFoodItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 187, 135, -1));

        tblMMCatalogue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Food Name", "Description", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMMCatalogue);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 250, 359, 171));

        btnMMDelete.setBackground(new java.awt.Color(31, 189, 214));
        btnMMDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMMDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnMMDelete.setText("DELETE");
        btnMMDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnMMDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 443, 135, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMMBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnMMBackActionPerformed

    private void txtMMPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMPriceActionPerformed

    private void btnMMAddFoodItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMAddFoodItemActionPerformed
        // TODO add your handling code here:
        for(Restaurant restro : ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
            if(restro.getUserName().equals(account.getUsername())){
                menu = ecosystem.getRestaurantDirectory().AddMenuDishes(restro, txtfMMFoodName.getText(), txtMMFoodDescription.getText(), txtMMPrice.getText());
            }
        }

        displayFoodCatalogue();

    }//GEN-LAST:event_btnMMAddFoodItemActionPerformed

    private void btnMMDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMMCatalogue.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Confirm delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){

                for(Restaurant restro:ecosystem.getRestaurantDirectory().getRestaurantDirectory()){
                    if(restro.getUserName().equals(account.getUsername())){
                        ecosystem.getRestaurantDirectory().DeleteDishes(restro, menu);
                    }
                }
                displayFoodCatalogue();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a row to proceed for deletion");
        }

    }//GEN-LAST:event_btnMMDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMMAddFoodItem;
    private javax.swing.JButton btnMMBack;
    private javax.swing.JButton btnMMDelete;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMMFoodDesc;
    private javax.swing.JLabel lblMMFoodname;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTable tblMMCatalogue;
    private javax.swing.JTextField txtMMFoodDescription;
    private javax.swing.JTextField txtMMPrice;
    private javax.swing.JTextField txtfMMFoodName;
    // End of variables declaration//GEN-END:variables

    public void displayFoodCatalogue() {
        DefaultTableModel tablemodel = (DefaultTableModel) tblMMCatalogue.getModel();
        tablemodel.setRowCount(0);
        for (Restaurant restro:ecosystem.getRestaurantDirectory().getRestaurantDirectory()) {
            if (restro.getUserName().equals(account.getUsername())) {
                System.out.println("1");
                if(!(restro.getMenu().isEmpty())){
                    for(Dishlist menu:restro.getMenu()){
                        System.out.println("2");
                        Object[] row = new Object[3];
                        row[0] = menu.getName();
                        row[1] = menu.getDetails();
                        row[2] = menu.getOrderAmount();
                        tablemodel.addRow(row);
                    }
                }
            }
        }
    }
}
